[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.dotfiles/themes/matugen/hyprland.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.dotfiles/themes/matugen/waybar.css'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.dotfiles/themes/matugen/alacritty.toml'

[templates.mako]
input_path = '~/.config/matugen/templates/mako.ini'
output_path = '~/.dotfiles/themes/matugen/mako.ini'
post_hook = 'makoctl reload'

[templates.waypaper]
input_path = '~/.config/matugen/templates/waypaper.css'
output_path = '~/.dotfiles/themes/matugen/waypaper.css'

[templates.walker]
input_path = '~/.config/matugen/templates/walker.css'
output_path = '~/.dotfiles/themes/matugen/walker.css'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.dotfiles/themes/matugen/ghostty.theme'

# [templates.gtk3]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
# output_path = '~/.config/gtk-3.0/gtk.css'
#
# [templates.gtk4]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
# output_path = '~/.config/gtk-4.0/gtk.css'

# [templates.qt5ct]
# input_path = '~/.config/matugen/templates/qtct-colors.conf'
# output_path = '~/.config/qt5ct/colors/matugen.conf'
#
# [templates.qt6ct]
# input_path = '~/.config/matugen/templates/qtct-colors.conf'
# output_path = '~/.config/qt6ct/colors/matugen.conf'

# [templates.brave]
# pre_hook = '~/.dotfiles/bin/hyprland-close-windows-of-class brave-browser'
# input_path = '~/.config/matugen/templates/brave-matugen.sh'
# output_path = '/tmp/brave-color-change'
# post_hook = 'chmod +x /tmp/brave-color-change && /tmp/brave-color-change'
#
# [templates.vesktop]
# input_path = '~/.config/matugen/templates/midnight-discord.css'
# output_path = '~/.config/vesktop/themes/midnight-discord.css'



#[templates.neovim]
#input_path = '~/.config/matugen/templates/neovim.vim'
#output_path = '~/.cache/wal/colors-wal.vim'

